name: Backups to OneDrive
on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 23 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: setup SSH
      env: { SSH_AUTH_SOCK: /tmp/ssh_agent.sock }
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan ${{ secrets.NETCUP_SSH_HOST }} >> ~/.ssh/known_hosts
        ssh-agent -a $SSH_AUTH_SOCK
        ssh-add - <<< "${{ secrets.NETCUP_SSH_KEY }}"

    - name: Backup wordpress (files)
      env: { SSH_AUTH_SOCK: /tmp/ssh_agent.sock }
      run: ssh ${{ secrets.NETCUP_SSH_USER }}@${{ secrets.NETCUP_SSH_HOST }} "rm -f backups/wordpress.tgz && tar -zcvf backups/wordpress.tgz httpdocs/wordpress"

    - name: Backup wordpress (sql)
      env: { SSH_AUTH_SOCK: /tmp/ssh_agent.sock }
      run: ssh ${{ secrets.NETCUP_SSH_USER }}@${{ secrets.NETCUP_SSH_HOST }} "cd httpdocs/wordpress && ./wp-cli.phar db export ~/backups/wordpress.sql.zip"

    - name: Upload backup to OneDrive
      env: { SSH_AUTH_SOCK: /tmp/ssh_agent.sock }
      run: ssh ${{ secrets.NETCUP_SSH_USER }}@${{ secrets.NETCUP_SSH_HOST }} "~/bin-user/rclone -c ~/conf-user/rclone.conf copy ~/backups onedrive:backups/website"
