name: Backups to OneDrive
on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.NETCUP_SSH_KEY }}
    - name: setup SSH
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan ${{ secrets.NETCUP_SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Backup wordpress (files)
      run: ssh ${{ secrets.NETCUP_SSH_USER }}@${{ secrets.NETCUP_SSH_HOST }} "rm -f backups/wordpress.tgz && tar -zcvf backups/wordpress.tgz httpdocs/wordpress"

    - name: Backup wordpress (sql)
      run: ssh ${{ secrets.NETCUP_SSH_USER }}@${{ secrets.NETCUP_SSH_HOST }} "cd httpdocs/wordpress && ./wp-cli.phar db export ~/backups/wordpress.sql.zip"

    - name: Upload backup to OneDrive
      run: ssh ${{ secrets.NETCUP_SSH_USER }}@${{ secrets.NETCUP_SSH_HOST }} "~/bin-user/rclone --config ~/conf-user/rclone.conf --progress copy ~/backups onedrive:backups/website/$(date +'%Y-%m-%d')"

    - name: Delete old backups
      run: ssh ${{ secrets.NETCUP_SSH_USER }}@${{ secrets.NETCUP_SSH_HOST }} "~/bin-user/rclone --config ~/conf-user/rclone.conf delete --min-age 30d onedrive:backups/website && ~/bin-user/rclone --config ~/conf-user/rclone.conf rmdirs onedrive:backups/website"
